language: php
php:
  - 7.3
  - 7.4

before_script:
  - composer install
script:
  - vendor/bin/phpcs src/ -p --standard=PSR2 --report=summary
  - mkdir -p build/logs
  - vendor/bin/phpunit --configuration phpunit.xml --coverage-text

after_success:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'
